Repository PelicanPlatform/pelican, pull requests merged in 2023-12, with the labels that each got.

#441 Fix racing conditions in various director-related code and tests
  director/cache_ads_test.go
  director/director_api.go
  director/director_api_test.go
  director/redirect.go
  director/redirect_test.go
Labels: bug, test

#432 Fix doc missing space for client-usage.mdx
  docs/pages/client-usage.mdx
Labels: documentation

#430 Refactor director SD tests and add test for duplicated origins
  director/director_api.go
  director/redirect_test.go
Labels: test

#442 Refactor `generate` package
  generate/main.go
  generate/next_generator.go
  generate/param_generator.go
  param/param.go
Labels: internal

#431 Provide ConfigureOriginAPI a cancel context that can be cancelled on shutdown
  cmd/cache_serve.go
  cmd/director_serve.go
  cmd/origin_serve.go
  director/cache_ads_test.go
  director/origin_api_test.go
  metrics/xrootd_metrics.go
  origin_ui/origin_api.go
  xrootd/origin_test.go
Labels: internal

#458 Add `listServer` API to director Web UI
  cmd/director_serve.go
  director/director.go
  director/director_api_test.go
  director/director_test.go
Labels: enhancement

#447 Refactor file transfer tests into a utility class
  director/origin_monitor.go
  origin_ui/self_monitor.go
  utils/test_file_transfers_utils.go
  xrootd/origin_test.go
Labels: internal

#469 Arm-compatible Pelican container and fix 404 minio RPM
  images/Dockerfile
  images/dev.Dockerfile
Labels: bug, infrastructure

#429 Refactor `checkAPIToken` to be more generic and less verbose
  director/director_api.go
  director/origin_api.go
  go.mod
  utils/server_auth.go
  utils/server_auth_test.go
  web_ui/authentication.go
  web_ui/authorization.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
Labels: bug, internal

#491 Exclude node_modules from calculating Next.js hash in GHA
  .github/workflows/test.yml
Labels: bug

#499 Rename `namespace_registry` to `registry`
  cmd/registry.go
  cmd/registry_client.go
  cmd/registry_serve.go
  cmd/root.go
  namespaces/namespaces.go
  registry/client_commands.go
  registry/client_commands_test.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_ui.go
  registry/registry_ui_test.go
  server_ui/register_namespace.go
  server_ui/register_namespace_test.go
Labels: internal

#414 Add Oauth2 client with CILogon
  cmd/registry_serve.go
  config/config.go
  config/init_server_creds.go
  config/resources/defaults.yaml
  docs/parameters.yaml
  go.mod
  go.sum
  oauth2/device_auth.go
  oauth2/oidc_client.go
  web_ui/authentication.go
  web_ui/authorization.go
  web_ui/oauth2_client.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
Labels: enhancement

#483 Refactor and move token create logic to utils
  cmd/origin_token.go
  cmd/origin_token_test.go
  utils/token_utils.go
  utils/token_utils_test.go
Labels: internal

#494 Add topology component to Prometheus health metric
  cmd/director_serve.go
  cmd/registry_serve.go
  metrics/health.go
  metrics/topology.go
  utils/web_utils.go
Labels: enhancement

#493 Include cache in director's service discovery endpoint
  director/director_api.go
  director/redirect.go
  director/redirect_test.go
  web_ui/prometheus.go
Labels: enhancement

#503 Refactor `config.ServerType` to provide a globally accessible source for server(s) enabled
  cmd/cache.go
  cmd/director.go
  cmd/director_serve.go
  cmd/origin.go
  cmd/origin_reset_password_test.go
  cmd/origin_serve.go
  cmd/registry.go
  cmd/registry_serve.go
  config/config.go
  config/config_test.go
  registry/client_commands_test.go
  server_ui/register_namespace_test.go
  server_utils/server_struct.go
  web_ui/prometheus.go
  web_ui/ui.go
  web_ui/ui_test.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/origin_test.go
  xrootd/xrootd_config.go
Labels: internal

#542 Create `tempDir` for all config files to avoid file not found in test
  server_ui/register_namespace_test.go
Labels: bug

#540 Unpublish Go package
  go.mod
Labels: infrastructure

#539 Rename `Federation.NamespaceUrl` to `Federation.RegistryUrl`
  cmd/registry_client.go
  config/config.go
  config/config_test.go
  director/origin_api.go
  director/origin_api_test.go
  director/redirect_test.go
  docs/parameters.yaml
  registry/client_commands_test.go
  server_ui/register_namespace.go
  server_ui/register_namespace_test.go
Labels: enhancement

#549 Only build and publish containers as well as releasing on tags >=`7.0.0` in GHA
  .github/workflows/publish-container.yml
  .github/workflows/publish-dev-container.yml
  .github/workflows/release.yml
Labels: infrastructure

#554 Fix error in retracting pkg with not including previous versions
  go.mod
Labels: infrastructure

#527 Replace `xrd-http` plugin by `xrdcl-pelican` plugin in dev-container
  images/Dockerfile
  images/dev.Dockerfile
Labels: infrastructure

#569 Reload TLS certificates as needed
  cmd/cache.go
  cmd/cache_serve.go
  cmd/director.go
  cmd/director_serve.go
  cmd/origin.go
  cmd/origin_reset_password_test.go
  cmd/origin_serve.go
  cmd/registry.go
  cmd/registry_serve.go
  config/config.go
  config/config_test.go
  go.mod
  registry/client_commands_test.go
  server_ui/register_namespace_test.go
  server_utils/server_utils.go
  utils/ca_utils.go
  web_ui/engine_test.go
  web_ui/ui.go
  web_ui/ui_test.go
  xrootd/authorization_test.go
  xrootd/origin_test.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/resources/xrootd-origin.cfg
  xrootd/xrootd_config.go
  xrootd/xrootd_config_test.go
Labels: enhancement
