Repository PelicanPlatform/pelican, pull requests merged in 2023-11, with the labels that each got.

#321 Fix bypassed authentication for /config API
  origin_ui/origin.go
Labels: bug

#289 Director Prometheus scraper of origins' metrics
  cmd/director_serve.go
  cmd/namespace_registry_serve.go
  cmd/origin_serve.go
  config/init_server_creds.go
  director/director_api.go
  director/redirect.go
  director/redirect_test.go
  web_ui/prometheus.go
  web_ui/ui.go
Labels: enhancement

#284 Api view
  origin_ui/src/README.md
  origin_ui/src/app/(dashboard)/Sidebar.tsx
  origin_ui/src/app/(dashboard)/config/page.tsx
  origin_ui/src/app/(dashboard)/layout.tsx
  origin_ui/src/app/globals.css
  origin_ui/src/package-lock.json
  origin_ui/src/public/theme.tsx
Labels: enhancement

#295 Automatically register origin with the namespace daemon
  cmd/cache_serve.go
  cmd/namespace_client.go
  cmd/origin_serve.go
  cmd/origin_token.go
  config/init_server_creds.go
  director/director_api.go
  director/origin_api.go
  director/origin_api_test.go
  director/redirect_test.go
  go.mod
  go.sum
  namespace-registry/client_commands.go
  namespace-registry/registry-db.go
  namespace-registry/registry.go
  origin_ui/origin.go
  origin_ui/register_origin.go
  origin_ui/register_origin_test.go
  origin_ui/self_monitor.go
  utils/server_utils.go
  web_ui/authorization.go
  web_ui/prometheus_test.go
Labels: enhancement

#369 Fix issue with progress bar panic on download
  client/handle_http.go
Labels: bug

#375 Always generate a CA if no host certificate present
  config/config.go
  config/config_default.go
  config/config_linux.go
  config/init_server_creds.go
  docs/parameters.yaml
Labels: bug

#373 Add authorization to Prometheus /metrics endpoint
  config/config.go
  config/resources/defaults.yaml
  director/director_api.go
  director/director_api_test.go
  docs/parameters.yaml
  origin_ui/origin.go
  web_ui/authorization.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
  web_ui/ui.go
Labels: enhancement

#358 Set correct log level for Prometheus logger
  go.mod
  go.sum
  web_ui/prometheus.go
Labels: bug

#376 Introduce enum for health status and component names for SetComponentHealthStatus
  cmd/cache.go
  cmd/cache_serve.go
  cmd/origin.go
  cmd/origin_serve.go
  daemon/launch_unix.go
  metrics/health.go
  metrics/health_test.go
  origin_ui/advertise.go
  origin_ui/register_origin.go
  origin_ui/self_monitor.go
Labels: internal

#382 Refactor init_server_cred to be more clear on their usage
  cmd/namespace_client.go
  cmd/namespace_registry_test.go
  cmd/origin_token_test.go
  config/config.go
  config/init_server_creds.go
  director/authentication.go
  director/director_api.go
  director/origin_api_test.go
  director/redirect_test.go
  docs/parameters.yaml
  origin_ui/origin_test.go
  origin_ui/register_origin_test.go
  web_ui/prometheus_test.go
  xrootd/authorization.go
Labels: internal

#400 Fix small bugs in DiscoverFederation()
  config/config.go
Labels: bug

#401 Add swagger spec and include auth APIs and common APIs
  swagger/pelican-swagger.yaml
Labels: enhancement

#378 Replace ComputeExternalAddress by param Server.ExternalWebUrl and rename Server.Port and Server.Address
  cmd/root.go
  config/config.go
  config/config_test.go
  config/resources/defaults.yaml
  director/director_api.go
  docs/parameters.yaml
  oa4mp/serve.go
  origin_ui/advertise.go
  origin_ui/origin.go
  web_ui/authorization.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
  web_ui/ui.go
Labels: bug, enhancement

#347 Add unit tests to XRootD monitoring handler
  metrics/xrootd_metrics.go
  metrics/xrootd_metrics_serializer.go
  metrics/xrootd_metrics_test.go
Labels: test

#398 Refactor origin_ui to web_ui to reuse basic logic for server web UI/API
  cmd/director_serve.go
  cmd/namespace_registry_serve.go
  cmd/origin_reset_password.go
  cmd/origin_reset_password_test.go
  cmd/origin_serve.go
  config/config.go
  docs/parameters.yaml
  origin_ui/origin.go
  origin_ui/src/app/initialization/code/page.tsx
  origin_ui/src/app/initialization/password/page.tsx
  origin_ui/src/app/login/page.tsx
  origin_ui/src/helpers/login.tsx
  swagger/pelican-swagger.yaml
  web_ui/authentication.go
  web_ui/prometheus.go
  web_ui/ui.go
  web_ui/ui_test.go
  web_ui/ui_unix.go
  web_ui/ui_windows.go
Labels: internal

#305 Director-based origin health tests
  cmd/director_serve.go
  cmd/origin_serve.go
  config/config.go
  director/authentication.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director_api.go
  director/origin_api.go
  director/origin_monitor.go
  director/redirect.go
  go.mod
  go.sum
  metrics/health.go
  namespace-registry/registry.go
  origin_ui/origin.go
  origin_ui/origin_api.go
  origin_ui/self_monitor.go
  origin_ui/src/components/StatusBox.tsx
  xrootd/authorization.go
  xrootd/xrootd_config.go
Labels: enhancement

#395 Always unmarshall config when /config API is called
  config/config.go
  param/param.go
Labels: bug

#422 Update integration test file
  tests/citests.sh
Labels: test

#416 Ensure TTL caches evict expired item
  cmd/cache_serve.go
  cmd/director_serve.go
  cmd/origin_serve.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director_api.go
  director/origin_api_test.go
  metrics/xrootd_metrics.go
  xrootd/origin_test_linux.go
  xrootd/xrootd_config.go
Labels: bug, test
