Repository PelicanPlatform/pelican, pull requests merged in 2023-09, with the labels that each got.

#115 Fix bug with common transport TLSSkipVerify
  handle_http.go
Labels: bug

#138 Bump linter timeout to 3m
  .golangci.yaml
Labels: infrastructure

#139 Run pre-commit against entire repo
  .github/workflows/release.yml
  Makefile
  cmd/director.go
  cmd/namespace_registry.go
  cmd/resources/xrootd.cfg
  config/resources/defaults.yaml
  config/resources/osdf.yaml
  docs/parameters.yaml
  images/entrypoint.sh
  images/supervisord/pelican_director_serve.conf
  images/supervisord/pelican_registry_serve.conf
  images/supervisord/supervisord.conf
  origin_ui/src/README.md
  origin_ui/src/app/initialization/code/CodeInput.tsx
  origin_ui/src/app/initialization/code/LoadingButton.tsx
  origin_ui/src/app/initialization/password/PasswordInput.tsx
  origin_ui/src/app/initialization/password/page.tsx
  origin_ui/src/app/page.module.css
  origin_ui/src/components/layout/Header.tsx
  origin_ui/src/components/progress-pager.tsx
  origin_ui/src/public/next.svg
  origin_ui/src/public/theme.tsx
  origin_ui/src/public/vercel.svg
  resources/10-stash-plugin.conf
  resources/opensciencegrid.org.pub
  resources/update-namespaces.sh
  tests/citests.sh
Labels: internal

#152 Fixed Generate Private Key Problems in Windows
  config/init_server_creds.go
  config/privs.go
Labels: bug, enhancement

#156 Updated test.yml to attach code coverage to the action summary
  .github/workflows/test.yml
Labels: enhancement, internal

#133 Add a variety of configurable parameters to docs
  docs/parameters.yaml
Labels: documentation

#142 Match ns prefix by longest match, not first match
  director/cache_ads.go
  director/cache_ads_test.go
Labels: bug

#158 Remove errant stdout message
  config/encrypted.go
Labels: bug

#149 First step toward self-testing: configure authorization
  config/config.go
  go.mod
  go.sum
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/resources/scitokens.cfg
  xrootd/resources/test-scitokens-2issuers.cfg
  xrootd/resources/test-scitokens-empty.cfg
  xrootd/resources/test-scitokens-issuer.cfg
  xrootd/resources/test-scitokens-monitoring.cfg
Labels: internal

#154 Test Origin Login APIs
  origin_ui/origin_test.go
Labels: internal

#162 Remove redundant viper call
  config/config.go
Labels: internal

#161 Fix federation auto-discovery bug
  config/config.go
Labels: bug
