Repository PelicanPlatform/pelican, pull requests merged in 2023-10, with the labels that each got.

#165 Removed `isDir` from handle_http.go
  handle_http.go
Labels: internal

#164 Turetske/parameter generation
  .github/workflows/golangci-lint.yml
  .gitignore
  Makefile
  cmd/director_serve.go
  cmd/namespace_client.go
  cmd/namespace_registry_serve.go
  cmd/origin_serve.go
  config/config.go
  config/init_server_creds.go
  director/advertise.go
  director/origin_api.go
  director/sort.go
  docs/parameters.yaml
  generate/param_generator.go
  handle_http.go
  main.go
  namespace-registry/registry-db.go
  namespace-registry/registry.go
  namespaces/namespaces.go
  origin_ui/advertise.go
  origin_ui/origin.go
  param/param.go
  web_ui/prometheus.go
  web_ui/ui.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/launch.go
  xrootd/launch_linux.go
Labels: internal

#157 Expose CLI for creating tokens
  cmd/origin.go
  cmd/origin_token.go
  cmd/origin_token_test.go
Labels: enhancement

#160 Added tests for the three functions in origin_api.go
  director/origin_api_test.go
  director/redirect_test.go
Labels: test

#163 Add development Dockerfile
  .github/workflows/publish-dev-container.yml
  images/dev-config.yaml
  images/dev.Dockerfile
Labels: infrastructure

#183 Pelican transport fixes and generated after configs
  client/director.go
  client/handle_http.go
  config/config.go
  namespace-registry/client_commands.go
  origin_ui/advertise.go
Labels: bug, internal

#167 Origin self-test
  client/handle_http.go
  cmd/origin_serve.go
  cmd/origin_token.go
  cmd/resources/xrootd.cfg
  config/config.go
  config/config_default.go
  config/config_linux.go
  config/init_server_creds.go
  config/resources/defaults.yaml
  director/origin_api.go
  director/origin_api_test.go
  director/redirect_test.go
  metrics/health.go
  namespace-registry/client_commands.go
  origin_ui/advertise.go
  origin_ui/origin.go
  origin_ui/self_monitor.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/launch.go
  xrootd/resources/test-scitokens-monitoring.cfg
Labels: enhancement

#176 Put prometheus metrics behind federation/origin token
  config/config.go
  director/redirect_test.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
Labels: enhancement

#191 Fix template rendering failure
  cmd/origin_serve_test.go
Labels: bug

#186 fixed typos within plugin_stage.go
  cmd/plugin_stage.go
Labels: bug

#217 Federation component health status
  origin_ui/advertise.go
Labels: enhancement

#243 Cleanup of pelican config files
  cmd/config_mgr.go
  cmd/object_copy.go
  cmd/plugin.go
  cmd/root.go
  config/config.go
  config/config_test.go
  xrootd/authorization_test.go
Labels: enhancement

#242 Documentation for user installation of the Pelican Client
  docs/pages/install.mdx
Labels: documentation

#249 Add first draft of client usage docs
  docs/pages/client-usage.mdx
Labels: documentation

#254 Expose director's public key via Open ID style URLs
  cmd/director_serve.go
  cmd/namespace_registry_serve.go
  director/authentication.go
  director/director_api.go
  director/redirect.go
Labels: enhancement

#245 Origin Installation Documentation
  docs/pages/serving_an_origin.mdx
  docs/public/invalid_certificate.png
  docs/public/metrics_view.png
  docs/public/origin_start.png
Labels: documentation

#236 Make default log level part of pelican config
  cmd/main.go
  config/config.go
  config/resources/defaults.yaml
  docs/parameters.yaml
Labels: enhancement

#252 Improve test of stash_plugin to be more like HTCSS environment
  tests/citests.sh
Labels: internal

#286 Fix dev container build failure by specify base image platform
  images/dev.Dockerfile
Labels: bug

#273 Move npm path placeholder creation from GHA to Go
  .github/workflows/golangci-lint.yml
  generate/next_generator.go
  generate/param_generator.go
  param/param.go
Labels: infrastructure

#267 Add some documentation on developing the website
  origin_ui/src/README.md
  origin_ui/src/dev/nginx.conf
  origin_ui/src/dev/run.sh
Labels: infrastructure

#268 Auto-generate config struct from parameters.yaml and provide REST API
  .gitignore
  config/config.go
  generate/param_generator.go
  origin_ui/origin.go
  param/param.go
Labels: enhancement

#253 Web UI improvements
  cmd/origin.go
  cmd/origin_reset_password.go
  cmd/origin_reset_password_test.go
  cmd/origin_serve.go
  config/config.go
  config/resources/defaults.yaml
  docs/parameters.yaml
  origin_ui/origin.go
  origin_ui/origin_test.go
  origin_ui/origin_unix.go
  origin_ui/origin_windows.go
Labels: enhancement

#288 Add Web URL in origin's advertisement message
  director/advertise.go
  director/advertise_test.go
  director/cache_ads.go
  director/origin_api.go
  director/redirect.go
  director/redirect_test.go
  origin_ui/advertise.go
Labels: enhancement, internal
