Repository PelicanPlatform/pelican, pull requests merged in 2024-12, with the labels that each got.

#1793 Fix documentation for the `Origin.Scitokens*` parameters
  docs/parameters.yaml
Labels: bug, documentation

#1772 Fix OSDF Director startup warnings and separate GeoIP metric collection
  director/cache_ads.go
  director/sort.go
  director/sort_test.go
Labels: bug, director

#1753 Add Version info to ServerAd
  cache/advertise.go
  director/director.go
  director/director_test.go
  origin/advertise.go
  server_structs/director.go
Labels: enhancement

#1797 Remove unnecessary OA4MP set up from the container entrypoint script
  images/entrypoint.sh
Labels: bug, origin

#1814 Remove each progress bar immediately upon completion
  cmd/progress_bars.go
Labels: bug, client

#1800 Escape user and group names in issued tokens (#1494)
  oa4mp/resources/policies.qdl
Labels: bug, origin

#1792 Add a refresh interval to the origin exports
  web_ui/frontend/app/origin/page.tsx
  web_ui/frontend/components/DataExportTable.tsx
Labels: origin

#1790 Prevent snapshot from incrementing version
  .goreleaser.yml
Labels: bug

#1825 Rename Server.TLSCertificate to Server.TLSCertificateChain
  .goreleaser.yml
  config/config.go
  config/config_default.go
  config/config_linux.go
  config/init_server_creds.go
  docs/pages/federating-your-data.mdx
  docs/parameters.yaml
  launcher_utils/xrootd_servers.go
  param/parameters.go
  param/parameters_struct.go
  systemd/10-osdf-defaults.yaml
  web_ui/engine_test.go
  web_ui/ui.go
  xrootd/xrootd_config.go
  xrootd/xrootd_config_test.go
Labels: documentation

#1838 Bump containerized S3/HTTP backend version from v0.1.7 to v0.1.8
  github_scripts/osx_install.sh
  images/Dockerfile
  images/dev.Dockerfile
Labels: bug, enhancement, origin, container

#1832 Cleanup changes made from $HOME fixes from before
  cmd/config_printer/config_summary.go
  config/config.go
  config/config_test.go
  registry/client_commands_test.go
  xrootd/authorization_test.go
Labels: internal

#1831 Enable auto-generation of Lotman policies
  config/resources/defaults.yaml
  docs/parameters.yaml
  launchers/cache_serve.go
  lotman/lotman.go
  lotman/lotman_linux.go
  lotman/lotman_test.go
  lotman/resources/lots-config.yaml
  lotman/resources/malformed-lots-config.yaml
  param/parameters.go
  param/parameters_struct.go
  server_utils/server_utils.go
  server_utils/server_utils_test.go
  xrootd/xrootd_config.go
Labels: enhancement, cache, lotman

#1816 Implement Object Delete Command
  client/director.go
  client/director_test.go
  client/fed_linux_test.go
  client/fed_test.go
  client/handle_http.go
  client/main.go
  client/resources/origin-with-and-without-write.yaml
  cmd/config_mgr.go
  cmd/object_delete.go
  director/director.go
Labels: enhancement, client, director

#1827 Trigger release actions if tag matches new `-rc.X` prerelease tags
  .github/workflows/build-prod-container.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: infrastructure

#1843 Add PolicyDefinitions UI
  .github/scripts/validate-parameters/main.py
  web_ui/frontend/components/configuration/Fields/Field.tsx
  web_ui/frontend/components/configuration/Fields/ObjectField/PolicyDefinitionForm.tsx
  web_ui/frontend/components/configuration/Fields/ObjectField/index.tsx
  web_ui/frontend/components/configuration/Fields/StringSliceField.tsx
  web_ui/frontend/components/configuration/Fields/index.ts
Labels: web-ui
