Repository PelicanPlatform/pelican, pull requests merged in 2024-02, with the labels that each got.

#703 Add docs to Prometheus metrics
  docs/pages/_meta.json
  docs/pages/prometheus.mdx
Labels: documentation

#719 Overhaul token creation to use util token cfg interface
  client/handle_http_test.go
  director/director_api.go
  director/origin_api.go
  director/origin_api_test.go
  director/origin_monitor.go
  docs/scopes.yaml
  generate/scope_generator.go
  registry/client_commands.go
  server_ui/advertise.go
  token_scopes/token_scopes.go
  utils/test_file_transfers_utils.go
  utils/token_utils.go
  web_ui/authentication.go
  web_ui/authorization.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
Labels: internal

#716 Update advertisement
  cache_ui/advertise.go
  client/director.go
  client/director_test.go
  cmd/cache_serve.go
  director/ad_conversion.go
  director/ad_conversion_test.go
  director/advertise.go
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director_api.go
  director/director_api_test.go
  director/origin_api.go
  director/redirect.go
  director/redirect_test.go
  namespaces/namespaces.go
  origin_ui/advertise.go
  server_utils/server_struct.go
  utils/web_utils.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/resources/test-scitokens-cache-issuer.cfg
Labels: internal, critical

#746 Add pelican-server RPM
  .goreleaser.yml
Labels: critical

#748 Remove param docs that are not implemented
  docs/parameters.yaml
Labels: documentation, critical

#714 Expanding plugin error reporting from plugin to starter
  classads/classads.go
  client/handle_http.go
  client/handle_http_test.go
  client/handle_ingest.go
  client/main.go
  cmd/object_copy.go
  cmd/object_get.go
  cmd/object_put.go
  cmd/plugin.go
Labels: enhancement

#682 Added `stat` feature at the director
  .github/workflows/test.yml
  cache_ui/advertise.go
  cmd/cache_serve.go
  common/director.go
  config/config.go
  config/resources/defaults.yaml
  director/ad_conversion.go
  director/ad_conversion_test.go
  director/advertise.go
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_api.go
  director/director_api_test.go
  director/origin_api.go
  director/origin_monitor.go
  director/redirect.go
  director/redirect_test.go
  director/sort.go
  director/stat.go
  director/stat_test.go
  docs/parameters.yaml
  github_scripts/stat_test.sh
  origin_ui/advertise.go
  param/parameters.go
  param/parameters_struct.go
  server_utils/server_struct.go
  web_ui/authorization.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/ui.go
  xrootd/authorization.go
  xrootd/authorization_test.go
Labels: enhancement, critical, director

#772 Add knob to self test frequency
  config/resources/defaults.yaml
  docs/parameters.yaml
  origin_ui/self_monitor.go
  param/parameters.go
  param/parameters_struct.go
Labels: enhancement, origin

#774 Add rate-limiter to the login endpoint
  config/resources/defaults.yaml
  docs/parameters.yaml
  go.mod
  go.sum
  param/parameters.go
  param/parameters_struct.go
  web_ui/authentication.go
  web_ui/ui_test.go
Labels: enhancement

#792 Only create topology table at server start and update topology table 10m instead of 10ms
  config/resources/osdf.yaml
  registry/client_commands_test.go
  registry/registry_db.go
  registry/registry_db_test.go
Labels: bug, critical, registry

#770 Add documentation for serving a registry and director
  .pre-commit-config.yaml
  docs/pages/_meta.json
  docs/pages/install.mdx
  docs/pages/serving_a_federation.mdx
  docs/pages/serving_an_origin.mdx
  docs/parameters.yaml
  docs/public/director-homepage.png
  docs/public/registry-admin.png
  docs/public/registry-public.png
Labels: documentation

#812 Remove bucket requirement for S3 origins
  cmd/origin.go
  go.sum
  launchers/launcher.go
Labels: enhancement

#807 Install missing python39-pip dependency for /bin/pip-3.9
  images/dev.Dockerfile
Labels: infrastructure

#804 Integrate ORM and versioned DB migrations to registry
  go.mod
  go.sum
  registry/migrations/20240212192712_create_db_tables.sql
  registry/migrations/20240212194951_change_admin_metadata_default.sql
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
Labels: internal, critical, registry

#806 Rebuild OSG's xrootd RPM from source inside the dev container
  .github/workflows/publish-container.yml
  .github/workflows/publish-dev-container.yml
  images/dev.Dockerfile
Labels: infrastructure

#823 Add project to Prometheus file transfer metric
  docs/pages/prometheus.mdx
  metrics/xrootd_metrics.go
  metrics/xrootd_metrics_test.go
Labels: enhancement, origin

#830 Update GHA to allow manifest to be written to harbor
  .github/workflows/publish-container.yml
  .github/workflows/publish-dev-container.yml
Labels: bug, infrastructure

#832 Fix wrong parameter names for default and osdf config files
  config/resources/defaults.yaml
  config/resources/osdf.yaml
Labels: bug, critical, registry

#827 Remove nested gin status code writer in `cliRegisterNamespace`
  registry/registry.go
Labels: bug, critical

#837 Rename not rebuild binary for alias test
  cmd/main_test.go
Labels: test, internal

#815 Stage lotman
  images/Dockerfile
  images/dev.Dockerfile
Labels: enhancement

#834 Web-based config change - backend support
  cmd/cache_serve.go
  cmd/root.go
  config/config.go
  docs/parameters.yaml
  generate/param_generator.go
  launchers/launcher.go
  param/param.go
  param/parameters.go
  param/parameters_struct.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/ui.go
Labels: enhancement

#846 Set prerelease as true
  .goreleaser.yml
Labels: infrastructure

#848 Add API at the director to return the longest prefix match given a path
  common/director.go
  director/advertise.go
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_api.go
  director/director_api_test.go
  director/redirect.go
  director/redirect_test.go
  director/sort.go
  director/stat.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
Labels: enhancement, critical, director

#855 Replace broken test file path in docs
  docs/pages/client-usage.mdx
  docs/pages/install.mdx
Labels: documentation

#853 Add file transfer test result to director `/servers` endpoint
  director/director.go
  director/director_test.go
  director/origin_monitor.go
  director/redirect.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
Labels: enhancement, director

#833 Remove debugging log from xrootd metrics handler
  metrics/xrootd_metrics.go
Labels: bug, critical

#852 Fix duplicated server advertisement at the director
  common/director.go
  director/redirect.go
Labels: bug, critical
