Repository PelicanPlatform/pelican, pull requests merged in 2024-10, with the labels that each got.

#1601 Move s3 path style into s3.begin/s3.end blocks
  xrootd/resources/xrootd-origin.cfg
Labels: critical, origin

#1589 Add Pelican URL Parsing library to standardize how we handle pelican URLs
  .github/workflows/test.yml
  broker/token_utils.go
  client/acquire_token.go
  client/director.go
  client/director_test.go
  client/errorAccum.go
  client/fed_linux_test.go
  client/fed_test.go
  client/handle_http.go
  client/handle_http_test.go
  client/main.go
  client/main_test.go
  client/sharing_url.go
  client/sharing_url_test.go
  cmd/config_mgr.go
  cmd/object_copy.go
  cmd/object_get.go
  cmd/plugin.go
  cmd/registry_client.go
  config/config.go
  config/config_test.go
  director/director.go
  director/discovery.go
  director/discovery_test.go
  director/origin_api.go
  fed_test_utils/fed.go
  launcher_utils/advertise.go
  launcher_utils/advertise_test.go
  launcher_utils/register_namespace.go
  origin/origin_ui.go
  origin/reg_status.go
  origin/reg_status_test.go
  pelican_url/discovery.go
  pelican_url/discovery_test.go
  pelican_url/parse.go
  pelican_url/parse_test.go
  pelican_url/query.go
  pelican_url/query_test.go
  registry/registry.go
  registry/registry_test.go
  server_utils/registry.go
  token/token_verify.go
  utils/client.go
  utils/client_test.go
  utils/utils.go
Labels: internal, client, plugin

#1595 Use capabilities structs in various types of server ads
  director/advertise.go
  director/advertise_test.go
  director/director.go
  origin/advertise.go
  server_structs/director.go
  server_structs/director_test.go
Labels: internal

#1642 Install sssd-client in dev/prod containers
  images/Dockerfile
  images/dev.Dockerfile
Labels: container

#1655 Move sssd-client installation to final stage builder
  images/Dockerfile
Labels: critical, origin

#1658 Marked un-prefixed config options deprecated
  docs/parameters.yaml
  param/parameters.go
Labels: documentation, client

#1632 Director Redirection Prometheus Metric
  director/director.go
  metrics/director.go
Labels: enhancement, director

#1652 cleanup all tickers when they're no longer needed
  broker/client.go
  cmd/progress_bars.go
  director/advertise.go
  director/maxmind.go
  launcher_utils/advertise.go
  launcher_utils/register_namespace.go
  local_cache/local_cache.go
  server_utils/monitor.go
  server_utils/server_utils.go
  utils/ca_utils.go
  web_ui/authentication.go
  web_ui/prometheus.go
Labels: internal

#1653 Switch to use new Caps struct but still handle old JSON from Director
  server_structs/director.go
  server_structs/director_test.go
Labels: enhancement, critical, director

#1597 Plumb HTTPS backend through CLI and adjust it to use full storage prefixes
  client/fed_test.go
  client/resources/test-https-origin.yml
  cmd/origin.go
  cmd/plugin_test.go
  cmd/resources/test-https-origin.yml
  docs/parameters.yaml
  server_utils/origin.go
  xrootd/fed_test.go
  xrootd/resources/test-https-origin.yml
  xrootd/resources/xrootd-origin.cfg
Labels: enhancement, critical, origin

#1575 Enable caching of object existence queries
  cmd/fed_serve_cache_test.go
  config/resources/defaults.yaml
  director/cache_ads.go
  director/director.go
  director/stat.go
  director/stat_test.go
  docs/parameters.yaml
  local_cache/cache_test.go
  metrics/director.go
  param/parameters.go
  param/parameters_struct.go
  utils/errgroup.go
Labels: enhancement, director

#1681 Update s3 backend to include new multi_curl handler
  github_scripts/osx_install.sh
  images/Dockerfile
  images/dev.Dockerfile
Labels: critical, origin

#1670 Configurable Prometheus Retention
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  web_ui/prometheus.go
Labels: enhancement, cache, origin, director, registry

#1643 correct OA4MP storage directory permission
  oa4mp/serve.go
Labels: bug, critical, origin
