Repository PelicanPlatform/pelican, pull requests merged in 2024-11, with the labels that each got.

#1684 Improved `pelican_director_server_count` metric
  director/director.go
  director/director_api.go
  launchers/director_serve.go
  metrics/director.go
Labels: enhancement, director

#1669 Update registry.mdx
  docs/pages/operating-a-federation/registry.mdx
Labels: bug, documentation

#1700 Security patch
  web_ui/frontend/package-lock.json
  web_ui/frontend/package.json
Labels: security

#1649 Cleanup MacOS installation instructions
  docs/pages/federating-your-data.mdx
  docs/pages/install.mdx
  docs/pages/install/macos.mdx
Labels: documentation, Facilitation

#1707 IsDir Check to Prevent Creation of Empty Files on Object Uploads
  client/fed_linux_test.go
  client/handle_http.go
  cmd/plugin_test.go
Labels: bug, client

#1708 Fix `proj` label setting bug
  director/director.go
  director/director_test.go
  metrics/xrootd_metrics.go
  utils/utils.go
Labels: bug

#1743 Fix cache redirection metric over-collection bug
  director/director.go
Labels: bug, director

#1687 Uniform error handling
  web_ui/frontend/app/(login)/initialization/code/page.tsx
  web_ui/frontend/app/(login)/initialization/password/page.tsx
  web_ui/frontend/app/(login)/login/page.tsx
  web_ui/frontend/app/config/Config.tsx
  web_ui/frontend/app/director/components/DirectorCard.tsx
  web_ui/frontend/app/director/components/DirectorDropdown.tsx
  web_ui/frontend/app/director/page.tsx
  web_ui/frontend/app/layout.tsx
  web_ui/frontend/app/registry/cache/edit/page.tsx
  web_ui/frontend/app/registry/cache/register/page.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/BooleanField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/EnumerationField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/EpochTimeField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/IntegerField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/PubkeyField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/StringField.tsx
  web_ui/frontend/app/registry/components/CustomRegistrationField/index.d.ts
  web_ui/frontend/app/registry/components/CustomRegistrationField/index.tsx
  web_ui/frontend/app/registry/components/Form.tsx
  web_ui/frontend/app/registry/components/PostPage.tsx
  web_ui/frontend/app/registry/components/PutPage.tsx
  web_ui/frontend/app/registry/components/index.ts
  web_ui/frontend/app/registry/components/util.tsx
  web_ui/frontend/app/registry/denied/page.tsx
  web_ui/frontend/app/registry/namespace/edit/page.tsx
  web_ui/frontend/app/registry/namespace/register/page.tsx
  web_ui/frontend/app/registry/origin/edit/page.tsx
  web_ui/frontend/app/registry/origin/register/page.tsx
  web_ui/frontend/app/registry/page.tsx
  web_ui/frontend/app/test/page.tsx
  web_ui/frontend/components/AlertPortal.tsx
  web_ui/frontend/components/AlertProvider.tsx
  web_ui/frontend/components/CodeBlock.tsx
  web_ui/frontend/components/FederationOverview.tsx
  web_ui/frontend/components/Namespace/Card.tsx
  web_ui/frontend/components/Namespace/DeniedCard.tsx
  web_ui/frontend/components/Namespace/InformationDropdown.tsx
  web_ui/frontend/components/Namespace/PendingCard.tsx
  web_ui/frontend/components/Namespace/index.d.tsx
  web_ui/frontend/components/Namespace/index.tsx
  web_ui/frontend/components/ThemeProvider.tsx
  web_ui/frontend/components/layout/AuthenticatedContent.tsx
  web_ui/frontend/dev/image/nginx.conf
  web_ui/frontend/helpers/api.ts
  web_ui/frontend/helpers/get.ts
  web_ui/frontend/helpers/login.ts
  web_ui/frontend/helpers/util.ts
  web_ui/frontend/index.ts
Labels: enhancement

#1675 Decrement page if empty on Cardlist
  web_ui/frontend/components/CardList.tsx
Labels: enhancement, user-request
