Repository PelicanPlatform/pelican, pull requests merged in 2024-03, with the labels that each got.

#867 Redact tokens from the xrootd output
  config/logging.go
  config/logging_test.go
Labels: enhancement

#842 Registry updates
  web_ui/frontend/app/registry/cache/edit/page.tsx
  web_ui/frontend/app/registry/cache/register/page.tsx
  web_ui/frontend/app/registry/components/CacheForm.tsx
  web_ui/frontend/app/registry/components/Fields/InstitutionField.tsx
  web_ui/frontend/app/registry/components/Fields/PubkeyField.tsx
  web_ui/frontend/app/registry/components/Fields/index.tsx
  web_ui/frontend/app/registry/components/OriginForm.tsx
  web_ui/frontend/app/registry/layout.tsx
  web_ui/frontend/app/registry/namespace/components/NamespaceForm.tsx
  web_ui/frontend/app/registry/origin/edit/page.tsx
  web_ui/frontend/app/registry/origin/register/page.tsx
  web_ui/frontend/app/registry/page.tsx
  web_ui/frontend/components/Main.d.ts
  web_ui/frontend/components/Namespace.tsx
  web_ui/frontend/components/Namespace/Card.tsx
  web_ui/frontend/components/Namespace/CardList.tsx
  web_ui/frontend/components/Namespace/CardSkeleton.tsx
  web_ui/frontend/components/Namespace/CreateNamespaceCard.tsx
  web_ui/frontend/components/Namespace/InformationDropdown.tsx
  web_ui/frontend/components/Namespace/NamespaceIcon.tsx
  web_ui/frontend/components/Namespace/PendingCard.tsx
  web_ui/frontend/components/Namespace/index.d.tsx
  web_ui/frontend/components/Namespace/index.tsx
  web_ui/frontend/components/NamespaceTable.tsx
  web_ui/frontend/components/layout/SidebarSpeedDial.tsx
  web_ui/frontend/helpers/util.tsx
Labels: registry

#844 Reorganize project to have less intertwined internal dependency
  broker/token_utils.go
  client/handle_http_test.go
  cmd/fed_serve_cache_test.go
  cmd/origin_token.go
  common/director.go
  common/registry.go
  director/origin_api.go
  director/origin_api_test.go
  director/origin_monitor.go
  director/redirect.go
  director/redirect_test.go
  director/stat.go
  github_scripts/get_put_test.sh
  origin_ui/origin_api.go
  origin_ui/self_monitor.go
  registry/client_commands.go
  registry/registry.go
  registry/registry_ui_test.go
  server_ui/advertise.go
  server_ui/register_namespace.go
  server_utils/registry.go
  server_utils/registry_test.go
  server_utils/test_file_transfer.go
  test_utils/utils.go
  token/token_create.go
  token/token_create_test.go
  token/token_verify.go
  token/token_verify_test.go
  web_ui/authentication.go
  web_ui/authorization.go
  web_ui/prometheus.go
  web_ui/prometheus_test.go
  xrootd/origin_test.go
Labels: internal

#887 Remove `Federation.NamespaceUrl`
  config/config.go
  config/config_test.go
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
Labels: registry

#865 Add depth attribute to link header in redirect response
  client/handle_http_test.go
  director/redirect.go
  director/redirect_test.go
Labels: enhancement, critical, director

#891 Refactor integration test scripts to be more robust
  github_scripts/get_put_test.sh
  github_scripts/stat_test.sh
Labels: test

#862 Fix permission error in reloading the authdb
  web_ui/ui_unix.go
  web_ui/ui_unix_test.go
Labels: bug, critical

#861 Self-test for cache
  cache_ui/cinfo.go
  cache_ui/self_monitor.go
  config/resources/defaults.yaml
  docs/parameters.yaml
  launchers/cache_serve.go
  param/parameters.go
  param/parameters_struct.go
  server_utils/test_file_transfer.go
  xrootd/authorization.go
Labels: enhancement, cache

#888 Always log 500 error in web handlers
  director/director.go
  director/redirect.go
  registry/registry.go
  registry/registry_ui.go
Labels: internal, director, registry

#894 Add Metalink for redirect to origin
  director/redirect.go
  xrootd/origin_test.go
Labels: enhancement, director

#885 Clean up goroutines when fatal error occurs at server start
  cmd/root.go
  daemon/launch_unix.go
Labels: bug, critical, cache, origin

#883 Split container images by server type and replace supervisord by tini
  .dockerignore
  .github/workflows/build-dev-container.yml
  .github/workflows/build-prod-container.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-container.yml
  images/Dockerfile
  images/entrypoint.sh
  images/supervisord/pelican_cache_serve.conf
  images/supervisord/pelican_director_serve.conf
  images/supervisord/pelican_origin_serve.conf
  images/supervisord/pelican_registry_serve.conf
  images/supervisord/supervisord.conf
Labels: critical, container

#897 Add doc for setting up Grafana
  docs/pages/_meta.json
  docs/pages/grafana.mdx
  docs/public/grafana-add-data-source.png
  docs/public/grafana-data-source-configuration-advanced.png
  docs/public/grafana-data-source-configuration.png
  docs/public/grafana-menu-location.png
  docs/public/grafana-search-prometheus.png
  docs/public/import-dashboard.png
  docs/public/origin-dashboard-template.json
  docs/public/origin-dashboard.png
Labels: documentation

#903 Replace `pelican` with server name for production image
  .github/workflows/build-prod-container.yml
  images/entrypoint.sh
Labels: bug, critical, container

#826 Add user role icon to the side bar in UI
  web_ui/frontend/components/layout/Sidebar.tsx
Labels: enhancement, critical

#877 Replace ad-hoc token verification logic by token.Verify
  director/origin_api.go
  director/redirect.go
  director/redirect_test.go
  go.mod
  origin_ui/origin_api.go
  registry/registry.go
  token/token_verify.go
  token/token_verify_test.go
  web_ui/authorization.go
Labels: internal

#922 Fix production cache container failure at start up due to outdated xrootd
  images/Dockerfile
  launchers/launcher.go
Labels: bug, cache, container

#931 Fix Prometheus handler not called
  web_ui/authorization.go
  web_ui/prometheus_test.go
  web_ui/ui.go
Labels: bug, critical

#923 Hash external repository to invalidate build cache when there's an update
  images/Dockerfile
  images/dev.Dockerfile
Labels: bug, container

#936 Fix misplaced branch check in GHA
  .github/workflows/build-prod-container.yml
  .github/workflows/pre-release.yml
  images/Dockerfile
Labels: bug, critical, container

#940 Removed unused input tag in `release.yml`
  .github/workflows/pre-release.yml
Labels: bug, infrastructure, critical

#935 Upgrade golangci GHA version and turn off caching
  .github/workflows/pre-commit-linter.yml
Labels: bug, infrastructure

#942 Fix pelican plugin bug `no valid classads...`
  cmd/plugin.go
Labels: bug, client, critical

#947 Embed `serve` as default command to run the server container
  images/Dockerfile
  images/entrypoint.sh
Labels: critical, container

#912 Update documentation to serve an origin
  docs/pages/grafana.mdx
  docs/pages/serving_a_federation.mdx
  docs/pages/serving_an_origin.mdx
  docs/public/grafana-dashboard-origin.png
  docs/public/origin-otp.png
  docs/public/origin-setup-password.png
  docs/public/origin-web-dashboard.png
  docs/public/origin_start.png
Labels: documentation

#955 Correct the key for docker doc page
  docs/pages/install/_meta.json
Labels: documentation

#937 Remove `generate` package when releasing
  .github/workflows/release.yml
  images/Dockerfile
Labels: infrastructure

#952 Create tmp cinfo file for cache self test under the same folder as the final file
  cache_ui/self_monitor.go
Labels: bug, critical, cache

#915 API support for registry admin to delete a namespace registration
  registry/registry.go
  registry/registry_db.go
  registry/registry_ui.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
Labels: enhancement, registry

#965 Allow RSA key for TLS
  broker/client.go
  cmd/registry_client.go
  config/init_server_creds.go
  config/init_server_creds_test.go
  registry/registry.go
  registry/registry_ui_test.go
  web_ui/authentication_test.go
  xrootd/origin_test.go
Labels: bug, critical

#967 Revert changes that remove `generate` package
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: bug, infrastructure, critical

#924 Consolidate two `namespaceExists` DB function
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_ui.go
Labels: bug, registry

#933 Allow admin to configure filtering servers for redirecting traffic at the director
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_api.go
  director/director_api_test.go
  director/director_test.go
  docs/parameters.yaml
  launchers/director_serve.go
  param/parameters.go
  param/parameters_struct.go
  registry/registry.go
  registry/registry_ui.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
Labels: enhancement, director

#989 Redirect logging location reminder to stderr
  config/config.go
Labels: bug
