Repository PelicanPlatform/pelican, pull requests merged in 2024-01, with the labels that each got.

#496 Allow GeoIP overrides and fix server geoip randomization
  director/resources/geoip_overrides.yaml
  director/sort.go
  director/sort_test.go
  docs/parameters.yaml
Labels: enhancement

#515 Registry UI APIs
  cmd/registry_serve.go
  config/config.go
  config/csrf.go
  config/init_server_creds.go
  docs/parameters.yaml
  go.mod
  go.sum
  param/parameters.go
  param/parameters_struct.go
  registry/client_commands.go
  registry/client_commands_test.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_ui.go
  registry/registry_ui_test.go
  registry/registry_validation.go
  server_ui/register_namespace_test.go
  web_ui/authentication.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/oauth2_client.go
  web_ui/ui.go
Labels: enhancement

#576 Fix time zone difference in registry DB test
  registry/registry_db_test.go
Labels: bug, test

#589 Only run Origin start script when it's origin
  launchers/launcher.go
Labels: bug

#396 Return config values with types for /config API
  generate/param_generator.go
  param/param.go
  param/parameters_struct.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/ui.go
Labels: enhancement

#596 Move log for origin to the conditional block
  launchers/launcher.go
Labels: bug

#607 Re-enable S3 Origins
  launchers/launcher.go
Labels: enhancement

#600 Fix broken namespace registration with device code flow
  registry/registry.go
Labels: bug

#534 Better management of token scopes
  cmd/origin_token.go
  cmd/origin_token_test.go
  director/director.go
  director/director_api.go
  director/origin_api.go
  director/redirect_test.go
  docs/scopes.yaml
  generate/main.go
  generate/param_generator.go
  generate/scope_generator.go
  param/parameters_struct.go
  registry/client_commands.go
  registry/registry.go
  token_scopes/token_scope_utils.go
  token_scopes/token_scope_utils_test.go
  token_scopes/token_scopes.go
  utils/server_auth.go
  utils/server_auth_test.go
  utils/token_utils.go
  utils/token_utils_test.go
  web_ui/authentication.go
  web_ui/authorization.go
  web_ui/prometheus_test.go
Labels: documentation, internal

#532 Add storage volume Prometheus metrics from XRootD monitoring packets
  metrics/xrootd_metrics.go
  metrics/xrootd_metrics_test.go
Labels: enhancement

#617 Only check namespace exists when create
  registry/registry_ui.go
Labels: bug

#577 Director as the federation
  cmd/fed_serve_test.go
  config/config.go
  director/discovery.go
  docs/parameters.yaml
  utils/server_auth.go
  utils/server_auth_test.go
  web_ui/authorization.go
Labels: enhancement

#610 Add status filter to registry API, improve Swagger docs
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_ui.go
  registry/registry_ui_test.go
  web_ui/authentication.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/oauth2_client.go
  web_ui/ui.go
Labels: documentation, enhancement

#613 Roll back registry api from `v2.0` to `v1.0`
  cmd/registry_client.go
  director/origin_api.go
  director/origin_api_test.go
  director/redirect.go
  director/redirect_test.go
  registry/client_commands_test.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_test.go
  server_ui/register_namespace.go
  server_ui/register_namespace_test.go
Labels: bug

#619 Add user role to `/auth/whoami` response
  registry/registry_ui.go
  registry/registry_ui_test.go
  web_ui/authentication.go
  web_ui/authentication_test.go
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/ui_test.go
Labels: enhancement

#663 Main test now restores current version
  cmd/main_test.go
Labels: bug

#640 Improved common Web API endpoint
  config/config.go
  config/config_test.go
  launchers/launcher.go
  param/parameters_struct.go
  web_ui/frontend/app/(landing)/page.tsx
  web_ui/frontend/app/(login)/login/page.tsx
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/frontend/app/config/page.tsx
  web_ui/frontend/components/StatusBox.tsx
  web_ui/ui.go
Labels: bug, enhancement

#657 Clear/correct logging at program exit
  cmd/root.go
  daemon/launch_unix.go
Labels: enhancement

#673 Add `pre-commit` to dev container and GHA
  .github/workflows/pre-commit-linter.yml
  .gitignore
  docs/pages/index.mdx
  docs/pages/parameters.mdx
  generate/scope_generator.go
  images/Dockerfile
  images/dev-config.yaml
  images/dev-container-entrypoint.sh
  images/dev.Dockerfile
  param/parameters_struct.go
  token_scopes/token_scopes.go
  web_ui/frontend/README.md
  web_ui/frontend/app/api/docs/SwaggerUI.tsx
  web_ui/frontend/app/api/docs/page.tsx
  web_ui/frontend/app/api/docs/pelican-swagger.yaml
  web_ui/frontend/app/globals.css
  web_ui/frontend/app/registry/namespace/components/NamespaceForm.tsx
  web_ui/frontend/components/Cell.tsx
  web_ui/frontend/components/FederationOverview.tsx
  web_ui/frontend/components/Namespace.tsx
  web_ui/frontend/components/layout/AuthenticatedContent.tsx
  web_ui/frontend/components/layout/Drawer.tsx
  web_ui/frontend/components/layout/Sidebar.tsx
  web_ui/frontend/components/layout/UnauthenticatedContent.tsx
  web_ui/frontend/dev/data/pubkey.json
Labels: infrastructure

#649 Take a URL from config value to fetch institution list for Registry
  config/resources/defaults.yaml
  docs/parameters.yaml
  launchers/registry_serve.go
  param/parameters.go
  param/parameters_struct.go
  registry/registry_ui.go
  registry/registry_ui_test.go
Labels: enhancement

#497 Fix Origin UI RateGraph data loss/issues
  param/parameters_struct.go
  web_ui/frontend/app/origin/page.tsx
  web_ui/frontend/components/graphs/Graph.tsx
  web_ui/frontend/components/graphs/RateGraph.tsx
Labels: bug

#683 Fix linter failure on main
  param/parameters_struct.go
  web_ui/frontend/components/graphs/RateGraph.tsx
Labels: bug

#692 Add config param to change storage server registration retry delay
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  server_ui/register_namespace.go
Labels: enhancement

#708 Update various GHA actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit-linter.yml
  .github/workflows/publish-container.yml
  .github/workflows/publish-dev-container.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: infrastructure

#553 Fix mismatched kid between token and public jwks
  cmd/origin_reset_password_test.go
  config/config.go
  config/init_server_creds.go
  director/origin_api_test.go
  director/redirect_test.go
  registry/client_commands_test.go
  utils/server_auth.go
  utils/token_utils_test.go
  web_ui/authentication.go
  web_ui/prometheus_test.go
Labels: bug

#717 Improve test coverage for various registry UI API functions and bug fixes along the way
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_ui.go
  registry/registry_ui_test.go
  registry/registry_validation.go
  web_ui/authentication.go
Labels: test

#707 Use `pelican://` protocol for pss.origin setting in the cache
  .pre-commit-config.yaml
  cmd/cache_serve.go
  daemon/launch.go
  daemon/launch_unix.go
  github_scripts/osx_install.sh
  github_scripts/pelican_protocol.patch
  launchers/origin_serve.go
  xrootd/launch.go
  xrootd/origin_test.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/xrootd_config.go
Labels: enhancement

#704 Rename director metric label and metric help text
  director/origin_monitor.go
  metrics/director.go
Labels: bug

#685 Reject unapproved origin/caches based on config and more robust director error response
  client/handle_http_test.go
  cmd/fed_serve_test.go
  cmd/object_get_put_test.go
  config/resources/defaults.yaml
  config/resources/osdf.yaml
  director/origin_api.go
  director/origin_api_test.go
  director/redirect.go
  director/redirect_test.go
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
  registry/registry_test.go
  server_ui/advertise.go
Labels: bug, enhancement, critical

#734 Fix server exit status code and remove verbose log at the client
  cmd/root.go
  launchers/launcher.go
Labels: bug, critical

#735 Return 405 wherever it's supposed to be returned
  web_ui/ui.go
Labels: bug

#583 Update ns key discovery to follow openid-style lookups
  director/origin_api.go
  director/origin_api_test.go
  director/redirect_test.go
  registry/client_commands.go
  registry/registry.go
Labels: enhancement
