Repository PelicanPlatform/pelican, pull requests merged in 2025-03, with the labels that each got.

#2033 Build and test improvements
  .github/workflows/build-and-test.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-macos-windows.yml
  images/Dockerfile
Labels: test, infrastructure, internal

#2082 Fix index out of bound error in attrs.Files
  xrootd/launch_linux.go
Labels: bug

#2085 Fix `generate keygen` so that public keys included required fields
  cmd/generate_keygen.go
  cmd/generate_keygen_test.go
  config/init_server_creds.go
Labels: bug, client

#2077 Add RPM and Deb dependencies for the programs required to run the pre-install script
  .goreleaser.yml
Labels: infrastructure

#2087 Remove private keys from in-memory key management when key files are deleted
  config/init_server_creds.go
  config/init_server_creds_test.go
Labels: bug, cache, origin, director, registry, error messages

#2061 Use DiscoveryURL as token issuer for Prometheus scraping in Director
  web_ui/authorization.go
  web_ui/prometheus.go
Labels: bug, cache, origin, director, security, monitoring

#2102 Install `sssd-client` into both origin container images
  images/Dockerfile
Labels: bug, origin, container

#1889 Wrote up docs for pelican_director_geoip_errors
  docs/pages/monitoring-pelican-services/prometheus.mdx
Labels: documentation

#2096 Update xrootd version to xrootd-5.7.3-1.5.osg24
  images/Dockerfile
Labels: enhancement, critical

#2080 Add log buffering mechanism using Logrus hook
  cmd/main.go
  config/config.go
  logging/logging.go
Labels: enhancement

#2086 Create API token listing endpoint
  database/director.go
  server_structs/db.go
  swagger/pelican-swagger.yaml
  web_ui/ui.go
  web_ui/ui_test.go
Labels: enhancement, critical, director

#2106 Enable crc32 and crc32c algorithms
  xrootd/resources/xrootd-cache.cfg
  xrootd/resources/xrootd-origin.cfg
Labels: enhancement, cache, origin

#2072 Use the web port for the token issuer
  docs/pages/federating-your-data/generating-tokens.mdx
Labels: documentation, origin

#2083 Report origin/cache version info in Director display
  director/director_ui.go
Labels: director

#2100 Add config parameter to allow preferring OIDC ID token claims
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  web_ui/oauth2_client.go
Labels: enhancement, origin

#2092 Integrate XRootD OSS stats
  metrics/xrootd_metrics.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/resources/xrootd-origin.cfg
Labels: enhancement, cache, origin, monitoring

#2103 Enable support for multiple issuers per namespace
  cache/advertise.go
  client/main_test.go
  cmd/fed_serve_cache_test.go
  cmd/origin_token.go
  config/config.go
  docs/parameters.yaml
  fed_test_utils/fed.go
  github_scripts/stat_test.sh
  origin/advertise.go
  origin/self_monitor.go
  param/parameters.go
  param/parameters_struct.go
  server_utils/origin.go
  server_utils/origin_test.go
  test_utils/utils.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/origin_test.go
  xrootd/resources/multi-export-multi-issuers.yml
  xrootd/resources/single-export-no-issuers.yml
  xrootd/resources/single-export-one-issuer.yml
  xrootd/resources/test-scitokens-monitoring.cfg
  xrootd/xrootd_config.go
  xrootd/xrootd_config_test.go
Labels: enhancement, critical, origin, director, security

#2054 Start plumbing redirect choice info into Director's response body
  client/director.go
  director/cache_ads.go
  director/director.go
  director/sort.go
  director/sort_algorithms.go
  director/sort_algorithms_test.go
  director/sort_test.go
  server_structs/director.go
Labels: enhancement, client, director

#2091 Base64 encode the OAuth state to avoid a double URL-encoded string
  web_ui/oauth2_client.go
  web_ui/oauth2_client_test.go
Labels: bug, origin

#2023 Add support for multiple directors / HA federations
  .goreleaser.yml
  cache/advertise.go
  cmd/fed_serve_test.go
  cmd/plugin_test.go
  config/config.go
  config/resources/defaults.yaml
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_advertise.go
  director/director_advertise_test.go
  director/director_api.go
  director/director_api_test.go
  director/director_test.go
  director/director_ui_test.go
  director/discovery.go
  director/sort_test.go
  director/stat_stress_test.go
  director/stat_test.go
  docs/parameters.yaml
  docs/scopes.yaml
  fed_test_utils/fed.go
  fed_test_utils/resources/default.yaml
  go.mod
  go.sum
  launcher_utils/advertise.go
  launchers/launcher.go
  origin/advertise.go
  param/parameters.go
  param/parameters_struct.go
  pelican_url/discovery.go
  server_structs/director.go
  server_structs/director_test.go
  server_structs/xrootd_server.go
  server_utils/director_discovery.go
  server_utils/server_utils.go
  server_utils/server_utils_test.go
  server_utils/sitename.go
  server_utils/sitename_test.go
  token/token_create.go
  token/token_create_test.go
  token_scopes/token_scopes.go
  version/version.go
Labels: enhancement, critical, cache, origin, director

#2114 Fix signal interrupt handling in log buffering code
  cmd/root.go
  logging/logging.go
Labels: bug, internal

#2116 Fix client bug where schemeless pel URLs don't work with '-f' fed info
  client/main.go
  client/main_test.go
  pelican_url/discovery.go
  pelican_url/parse.go
Labels: bug, client

#2135 Add version to the director cards
  web_ui/frontend/app/director/components/DirectorDropdown.tsx
  web_ui/frontend/types.ts
Labels: enhancement

#2128 Fix `TestStatMemory` (maybe)
  director/stat_stress_test.go
Labels: bug, test, internal

#2141 Fix testing workflow for release candidates
  .github/workflows/build-and-test.yml
  .github/workflows/test-linux-pr.yaml
Labels: bug, infrastructure, critical

#2142 Use YAML for the debug-level config dumps
  config/config.go
Labels: bug, client, cache, origin

#1993 Update prometheus.mdx
  docs/pages/monitoring-pelican-services/prometheus.mdx
Labels: documentation

#2147 Move token endpoints behind auth
  web_ui/ui.go
  web_ui/ui_test.go
Labels: bug, create-patch

#2137 Align token endpoints with REST API best practices
  server_structs/db.go
  swagger/pelican-swagger.yaml
  web_ui/ui.go
  web_ui/ui_test.go
Labels: enhancement

#2105 Revise Prometheus Metric Names
  director/cache_ads.go
  director/director.go
  director/sort.go
  metrics/director.go
  metrics/xrootd_metrics.go
Labels: enhancement, monitoring

#2158 Fix director backwards compatibility
  server_utils/director_discovery.go
Labels: bug, cache, origin
