Repository PelicanPlatform/pelican, pull requests merged in 2025-10, with the labels that each got.

#2712 Fix bug preventing Origins with `Logging.Level: Warn` from starting
  config/config.go
  xrootd/xrootd_config.go
Labels: bug, cache, origin, configuration, create-patch

#2718 Bump xrootd-s3-http version
  github_scripts/osx_install.sh
  images/Dockerfile
Labels: dependencies, origin, container

#2725 Switch to installing the `pelican-server` binary in all server images
  images/Dockerfile
Labels: internal, container
