Repository PelicanPlatform/pelican, pull requests merged in 2025-04, with the labels that each got.

#2167 Add more events to response for long history issues
  .github/workflows/enforce-PR-labelling.yml
Labels: bug

#2118 Add PURGEFIRST functionality and reconstruct state from Data Location
  go.mod
  go.sum
  local_cache/cache_api.go
  local_cache/cache_linux_test.go
  local_cache/local_cache.go
Labels: enhancement

#1996 Downtime set by origin and cache
  cmd/fed_serve_test.go
  cmd/plugin_test.go
  database/downtime_utils.go
  database/migrations/20250219132824_create_db_tables.sql
  database/server.go
  database/server_test.go
  director/cache_ads.go
  director/director.go
  director/director_api.go
  director/director_db.go
  director/director_ui.go
  e2e_fed_tests/downtime_test.go
  fed_test_utils/fed.go
  origin/advertise.go
  server_structs/director.go
  swagger/pelican-swagger.yaml
  web_ui/server_api.go
  web_ui/server_api_test.go
  web_ui/ui.go
Labels: critical, cache, origin, director

#2180 Fix cache self-test error message & prevent file name truncation
  cache/self_monitor.go
Labels: test, cache

#1990 Origins on director
  web_ui/frontend/app/cache/metrics/page.tsx
  web_ui/frontend/app/cache/page.tsx
  web_ui/frontend/app/director/components/DirectorCard.tsx
  web_ui/frontend/app/director/metrics/cache/page.tsx
  web_ui/frontend/app/director/metrics/components/MetricBoxPlot.tsx
  web_ui/frontend/app/director/metrics/components/ServerUptime.tsx
  web_ui/frontend/app/director/metrics/components/StorageTable.tsx
  web_ui/frontend/app/director/metrics/components/TransferBarGraph.tsx
  web_ui/frontend/app/director/metrics/origin/page.tsx
  web_ui/frontend/app/director/metrics/page.tsx
  web_ui/frontend/app/origin/metrics/page.tsx
  web_ui/frontend/app/origin/page.tsx
  web_ui/frontend/components/CardList.tsx
  web_ui/frontend/components/DataTable.tsx
  web_ui/frontend/components/Namespace/Card.tsx
  web_ui/frontend/components/Namespace/NamespaceCardList.tsx
  web_ui/frontend/components/Namespace/PendingCard.tsx
  web_ui/frontend/components/ServerTable.tsx
  web_ui/frontend/components/StyledHeadTableCell.tsx
  web_ui/frontend/components/graphs/CacheMetricPage.tsx
  web_ui/frontend/components/graphs/Graph.tsx
  web_ui/frontend/components/graphs/GraphContext.tsx
  web_ui/frontend/components/graphs/LineGraph.tsx
  web_ui/frontend/components/graphs/OriginMetricPage.tsx
  web_ui/frontend/components/graphs/RateGraph.tsx
  web_ui/frontend/components/graphs/prometheus.tsx
  web_ui/frontend/components/metrics/CPUGraph.tsx
  web_ui/frontend/components/metrics/MemoryGraph.tsx
  web_ui/frontend/components/metrics/ProjectsTable.tsx
  web_ui/frontend/components/metrics/StorageGraph.tsx
  web_ui/frontend/components/metrics/TransferRateGraph.tsx
  web_ui/frontend/types.ts
Labels: enhancement

#2177 Sanity check received size and on-disk size for client GETs
  client/handle_http.go
  github_scripts/citests.sh
Labels: enhancement, client, critical, create-patch

#2196 Fix metrics scraping by accepting fed tokens for Director service discovery
  director/director.go
  director/director_test.go
  test_utils/utils.go
Labels: bug, cache, origin, director, security, monitoring, create-patch

#2189 Disable topology flags
  config/resources/osdf.yaml
  director/advertise.go
  director/advertise_test.go
  docs/parameters.yaml
  launchers/registry_serve.go
  param/parameters.go
  param/parameters_struct.go
  xrootd/authorization.go
  xrootd/authorization_test.go
Labels: enhancement, cache, origin, director, registry

#2185 Update 'componenets' for Monitoring.XXX configs
  docs/parameters.yaml
Labels: bug, documentation, monitoring

#2203 Add Warning Comment for Misaligned ServerAd and serverResponse structs
  director/director_ui.go
  server_structs/director.go
Labels: internal, director

#2174 Add user and group requirements to the built-in issuer's authorization templates
  docs/parameters.yaml
  oa4mp/resources/policies.qdl
  oa4mp/serve.go
Labels: enhancement, origin

#2182 Fix log level/location issues coming from web UI config
  cmd/main_test.go
  config/config.go
  config/config_test.go
  config/config_validation_test.go
  local_cache/cache_linux_test.go
  logging/logging.go
  registry/registry_ui_test.go
  server_utils/server_utils.go
  web_ui/authentication_test.go
  web_ui/server_api_test.go
  xrootd/authorization_test.go
Labels: bug, critical, web-ui, configuration

#2175 Add `CacheAuthz` feature to origins/caches and use in Director's matchmaking
  client/fed_test.go
  cmd/plugin_test.go
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_test.go
  director/director_ui.go
  director/sort.go
  director/sort_test.go
  director/stat.go
  director/stat_test.go
  docs/parameters.yaml
  features/feature_compatibility.go
  features/feature_compatibility_test.go
  features/features.go
  features/resources/feature-version-compatibility.yaml
  generate/main.go
  generate/server_features_generator.go
  github_scripts/stat_test.sh
  local_cache/cache_test.go
  origin/advertise.go
  origin/advertise_test.go
  param/parameters.go
  param/parameters_struct.go
  server_structs/director.go
  server_utils/origin.go
  server_utils/origin_test.go
  utils/ternary.go
Labels: enhancement, critical, cache, origin, director

#2197 Downtime CLI for server admin
  client/acquire_token.go
  cmd/director.go
  cmd/downtime.go
  cmd/downtime_create.go
  cmd/downtime_delete.go
  cmd/downtime_list.go
  cmd/downtime_update.go
  cmd/root.go
  database/server.go
  server_structs/director.go
  utils/utils.go
  web_ui/server_api.go
Labels: client, cache, origin

#2217 Make sure the server dblocation is in a tmpdir in NewFedTest
  fed_test_utils/fed.go
Labels: bug, critical

#2214 Add environment subpage to parameters
  docs/pages/parameters.mdx
Labels: documentation, configuration

#2173 Exclude namespace itself from its super/sub spaces & allow Registry admin to overwrite the public key of a namespace
  registry/registry_db.go
  registry/registry_ui.go
  registry/registry_ui_test.go
  registry/registry_validation_test.go
Labels: registry

#2222 Update xrootd to 5.8.1
  client/fed_test.go
  github_scripts/osx_install.sh
  images/Dockerfile
Labels: internal, critical, cache, origin

#2224 Create cache socket as temporary and overwrite
  fed_test_utils/fed.go
  local_cache/cache_api.go
  local_cache/cache_test.go
Labels: bug, cache

#2188 Create "Plugin" subpage of "Advanced Usage" in documentation
  docs/pages/advanced-usage/_meta.json
  docs/pages/advanced-usage/plugin.mdx
Labels: documentation, plugin, configuration

#2241 Prevent package dependencies from changing the XRootD install
  images/Dockerfile
Labels: bug, internal, container

#2204 XRootD config changes for v7.16
  xrootd/launch.go
  xrootd/launch_linux.go
  xrootd/resources/xrootd-cache.cfg
Labels: enhancement, critical, cache

#2243 Clean up Dependabot security alerts
  go.mod
  go.sum
Labels: internal, critical, security

#2234 Cache authz for origin scitokens
  server_utils/origin.go
  web_ui/authentication_test.go
  xrootd/authorization.go
  xrootd/authorization_test.go
  xrootd/resources/scitokens.cfg
Labels: critical, origin

#2247 Update packages to prevent dependabot security warnings
  .github/workflows/go-generate-check.yml
  .github/workflows/pre-commit-linter.yml
  .github/workflows/release.yml
  .github/workflows/test-macos-windows.yml
  Makefile
  go.mod
  go.sum
  images/Dockerfile
Labels: internal, container, security

#2211 Pelicanize "NEAREST_CACHE" env var with 'Client.PreferredCaches'
  cmd/cmd_utils.go
  cmd/object_copy.go
  cmd/object_get.go
  cmd/object_prestage.go
  cmd/object_sync.go
  cmd/plugin.go
  config/config.go
  docs/pages/advanced-usage/plugin.mdx
  docs/parameters.yaml
  github_scripts/citests.sh
  param/parameters.go
  param/parameters_struct.go
  utils/utils.go
Labels: client, critical, configuration

#2249 Update the version of golangci-lint used by pre-commit
  .pre-commit-config.yaml
Labels: test, internal

#2008 Handle `Lotman.LotHome` directory creation/permissions in Pelican
  config/config.go
  config/mkdirall.go
  docs/parameters.yaml
  lotman/lotman_linux.go
Labels: enhancement, critical, cache, lotman

#2251 Re-add sharp for all architectures
  images/Dockerfile
  web_ui/frontend/package-lock.json
  web_ui/frontend/package.json
Labels: bug, internal, container

#1896 Put the dynamically-linked pelican-server binary in the pelican-server RPM
  .goreleaser.yml
  systemd/osdf-cache.service
  systemd/osdf-origin.service
  systemd/pelican-cache.service
  systemd/pelican-origin.service
Labels: cache, origin

#2151 Token UI
  web_ui/frontend/app/director/components/DirectorCardList.tsx
  web_ui/frontend/app/navigation.tsx
  web_ui/frontend/app/settings/api/components/TokenForm.tsx
  web_ui/frontend/app/settings/api/components/TokenList.tsx
  web_ui/frontend/app/settings/api/page.tsx
  web_ui/frontend/app/settings/api/tokens/add/page.tsx
  web_ui/frontend/app/settings/components/SettingHeader.tsx
  web_ui/frontend/app/settings/components/SubNavigation.tsx
  web_ui/frontend/app/settings/components/Token.tsx
  web_ui/frontend/app/settings/layout.tsx
  web_ui/frontend/app/settings/page.tsx
  web_ui/frontend/components/CardList.tsx
  web_ui/frontend/components/layout/Navigation/index.ts
  web_ui/frontend/types.ts
Labels: enhancement

#2218 Downtime workflow for stateless Directors
  cache/advertise.go
  database/server.go
  database/server_test.go
  database/universal_migrations/20250407175156_server.sql
  director/advertise.go
  director/cache_ads.go
  director/director.go
  director/director_api.go
  director/director_db.go
  director/director_db_test.go
  director/director_test.go
  director/director_ui.go
  director/migrations/20241017135850_create_db_tables.sql
  e2e_fed_tests/downtime_test.go
  launchers/director_serve.go
  origin/advertise.go
  server_structs/director.go
  server_structs/topology.go
  swagger/pelican-swagger.yaml
  web_ui/server_api.go
  web_ui/server_api_test.go
  web_ui/ui.go
Labels: critical, director, registry

#2089 Populating structure of the FAQs
  docs/pages/faq.mdx
Labels: documentation, Facilitation

#2255 Extend login cookie to last for 16 hours
  web_ui/authentication.go
Labels: enhancement

#2259 Bugfixes, tests, and tools around checksums
  classads/classads.go
  classads/classads_test.go
  client/fed_test.go
  client/handle_http.go
  client/handle_http_test.go
  client/main.go
  cmd/object_stat.go
  cmd/plugin.go
  cmd/plugin_test.go
Labels: bug, enhancement, client, critical

#2235 Implement Prometheus health
  launchers/launcher.go
  metrics/health.go
  web_ui/prometheus.go
Labels: enhancement, monitoring

#2225 XRootD CPU Utilization Metric
  metrics/xrootd_metrics.go
Labels: enhancement, cache, origin, monitoring

#2274 Remove downtime toggles on Director
  web_ui/frontend/app/director/components/DirectorCard.tsx
  web_ui/frontend/app/director/components/DirectorCardList.tsx
  web_ui/frontend/app/director/components/DirectorDropdown.tsx
Labels: create-patch

#2228 Warn user if they still use the key file at `IssuerKey`
  config/config.go
Labels: bug, origin

#2275 Correctly compare the total local size with the total downloaded size
  client/handle_http.go
  client/handle_http_test.go
Labels: bug, create-patch
