Repository PelicanPlatform/pelican, pull requests merged in 2025-07, with the labels that each got.

#2436 Introduce client transfer statistics output
  client/handle_http.go
  client/handle_http_test.go
  cmd/object_get.go
  cmd/object_put.go
Labels: enhancement, client

#2457 When creating custom TLS certs, add IPs to SANs as IPs and not DNS names
  config/init_server_creds.go
Labels: bug, test, internal

#2437 Fix link depth header for listings
  director/director.go
  director/director_test.go
Labels: bug, critical, director

#2432 Local cache cleanup bug fixes
  local_cache/cache_api.go
Labels: bug

#2442 Mark additional errors as retry-able
  client/errorAccum.go
  client/handle_http.go
  client/handle_http_test.go
Labels: client, error messages, plugin

#2455 Added per operation scope checking
  client/acquire_token.go
  client/main_test.go
Labels: bug, client, create-patch

#2467 Web client - Origin and Cache changes
  xrootd/resources/xrootd-cache.cfg
  xrootd/resources/xrootd-origin.cfg
Labels: create-patch

#2035 Init config refactor
  broker/broker_test.go
  broker/token_utils_test.go
  client/director_test.go
  client/fed_long_test.go
  client/fed_test.go
  client/sharing_url_test.go
  cmd/config_printer/config_printer_test.go
  cmd/fed_serve_test.go
  cmd/origin_reset_password_test.go
  cmd/plugin.go
  cmd/plugin_test.go
  cmd/resources/public-test-origin.yml
  cmd/root.go
  config/config.go
  config/config_test.go
  config/config_validation_test.go
  director/director_test.go
  director/discovery_test.go
  director/fed_token_test.go
  director/origin_api_test.go
  director/stat_test.go
  fed_test_utils/fed.go
  launcher_utils/register_namespace_test.go
  lotman/lotman_test.go
  registry/client_commands_test.go
  registry/registry_db_test.go
  server_utils/origin.go
  server_utils/registry_test.go
  test_utils/utils.go
  token/token_create_test.go
  web_ui/authentication_test.go
  web_ui/engine_test.go
  web_ui/prometheus_test.go
  web_ui/ui_test.go
  xrootd/authorization_test.go
  xrootd/drop_privilege_test.go
  xrootd/origin_test.go
  xrootd/xrootd_config_test.go
Labels: internal

#2154 Add meaningful page titles
  web_ui/frontend/app/(landing)/layout.tsx
  web_ui/frontend/app/(login)/initialization/code/layout.tsx
  web_ui/frontend/app/(login)/initialization/password/layout.tsx
  web_ui/frontend/app/(login)/layout.tsx
  web_ui/frontend/app/api/docs/layout.tsx
  web_ui/frontend/app/cache/layout.tsx
  web_ui/frontend/app/config/layout.tsx
  web_ui/frontend/app/director/layout.tsx
  web_ui/frontend/app/director/map/layout.tsx
  web_ui/frontend/app/director/metrics/layout.tsx
  web_ui/frontend/app/layout.tsx
  web_ui/frontend/app/origin/globus/layout.tsx
  web_ui/frontend/app/origin/issuer/layout.tsx
  web_ui/frontend/app/origin/layout.tsx
  web_ui/frontend/app/registry/cache/edit/layout.tsx
  web_ui/frontend/app/registry/cache/register/layout.tsx
  web_ui/frontend/app/registry/denied/layout.tsx
  web_ui/frontend/app/registry/layout.tsx
  web_ui/frontend/app/registry/namespace/edit/layout.tsx
  web_ui/frontend/app/registry/namespace/register/layout.tsx
  web_ui/frontend/app/registry/origin/edit/layout.tsx
  web_ui/frontend/app/registry/origin/register/layout.tsx
  web_ui/frontend/components/layout/MetaLayout.tsx
Labels: enhancement

#2409 Downtime Upgrades
  web_ui/frontend/components/Downtime/DateTile.tsx
  web_ui/frontend/components/Downtime/DowntimeCalendar.tsx
  web_ui/frontend/components/Downtime/DowntimeEditContext.tsx
  web_ui/frontend/components/Downtime/EditDowntimePageHeader.tsx
  web_ui/frontend/components/Downtime/Registry/ServerUnknownDowntimeForm.tsx
  web_ui/frontend/components/Downtime/Server/DowntimeForm.tsx
  web_ui/frontend/components/Downtime/calendar.css
  web_ui/frontend/helpers/Registry/namespaceToServer.ts
  web_ui/frontend/helpers/getDaysInMonth.ts
  web_ui/frontend/helpers/getUtcOffsetString.ts
  web_ui/frontend/index.ts
  web_ui/frontend/package-lock.json
  web_ui/frontend/package.json
Labels: registry, web-ui

#2468 Web client - All Changes
  client/acquire_token.go
  director/director.go
  docs/parameters.yaml
  images/Dockerfile
  oa4mp/proxy.go
  oa4mp/resources/authorize-remote-user.jsp
  oa4mp/resources/device-consent.jsp
  oa4mp/resources/device-fail.jsp
  oa4mp/resources/device-ok.jsp
  param/parameters.go
  param/parameters_struct.go
  server_structs/director.go
  server_utils/oidc.go
Labels: enhancement, critical

#2501 Install xrootd-lotman and lotman from osg repos
  images/Dockerfile
Labels: bug, dependencies, cache, lotman

#2488 Enable CGO for the binary build that includes purego
  .github/workflows/test-linux.yml
  .goreleaser.yml
  launchers/droppriv_unix.go
Labels: cache, lotman

#2400 Multiple Director Bug Fixes
  director/director.go
  director/director_advertise.go
  director/forward_service_test.go
  server_structs/director.go
  server_utils/sitename.go
  server_utils/test_file_transfer.go
Labels: bug, director

#2484 Follow symlink to load private key
  config/init_server_creds.go
  config/init_server_creds_test.go
Labels: bug, client, cache, origin, director, registry

#2513 Improve deprecated parameter handling in `pelican config get`
  cmd/config_printer/config_get.go
  cmd/config_printer/config_printer_root.go
Labels: client

#2525 Bump XRootD to v5.8.4-1.2 and install xrdcl-pelican from repos
  github_scripts/osx_install.sh
  images/Dockerfile
Labels: dependencies, cache, origin, container, create-patch

#2526 Use the correct `ver` claim in scitoken verification
  client/acquire_token.go
Labels: bug

#2428 Improvements for HTTP transports and stat tests
  .github/workflows/test-linux.yml
  .github/workflows/test-macos-windows.yml
  client/director.go
  client/fed_long_test.go
  client/fed_test.go
  client/handle_http.go
  client/main.go
  config/transport.go
  daemon/launch.go
  daemon/launch_unix.go
  director/cache_monitor.go
  director/director_advertise.go
  director/director_advertise_test.go
  director/stat.go
  director/stat_stress_test.go
  director/stat_test.go
  launcher_utils/advertise.go
  local_cache/cache_authz.go
  pelican_url/discovery.go
  xrootd/launch.go
  xrootd/launch_linux.go
Labels: test, client

#2278 Fixes login handling for Origin and Cache
  web_ui/frontend/app/(login)/403/page.tsx
  web_ui/ui.go
  web_ui/ui_test.go
Labels: bug, cache, origin
