Repository PelicanPlatform/pelican, pull requests merged in 2025-01, with the labels that each got.

#1865 Update install.mdx
  docs/pages/install.mdx
Labels: documentation

#1856 Packaging: create pelican user and group and some directories for it
  .goreleaser.yml
  scripts/preinstall-alpine.sh
  scripts/preinstall.sh
Labels: enhancement, infrastructure, cache, origin, director, registry

#1857 Install xrdcl-pelican from osg-testing instead of building it from source
  images/Dockerfile
Labels: infrastructure, container

#1864 Run release action against triggering tag instead of checking out branch
  .github/workflows/release.yml
Labels: bug, infrastructure

#1872 Fix logic for handling deprecated configuration parameters
  config/config.go
  config/config_test.go
  docs/parameters.yaml
Labels: bug

#1876 Fix submodule init ordering for S3/HTTP plugins in dev/prod containers
  images/Dockerfile
  images/dev.Dockerfile
Labels: bug, infrastructure, container

#1815 Make website mobile friendly
  web_ui/frontend/app/(landing)/page.tsx
  web_ui/frontend/app/(login)/components/CodeInput.tsx
  web_ui/frontend/app/(login)/components/PasswordInput.tsx
  web_ui/frontend/app/(login)/layout.tsx
  web_ui/frontend/app/(login)/login/page.tsx
  web_ui/frontend/app/cache/layout.tsx
  web_ui/frontend/app/config/Config.tsx
  web_ui/frontend/app/config/layout.tsx
  web_ui/frontend/app/director/layout.tsx
  web_ui/frontend/app/director/metrics/page.tsx
  web_ui/frontend/app/layout.tsx
  web_ui/frontend/app/navigation.tsx
  web_ui/frontend/app/origin/layout.tsx
  web_ui/frontend/app/origin/metrics/page.tsx
  web_ui/frontend/app/registry/layout.tsx
  web_ui/frontend/components/DataExportTable.tsx
  web_ui/frontend/components/Namespace/Card.tsx
  web_ui/frontend/components/Namespace/PendingCard.tsx
  web_ui/frontend/components/NamespaceCapabilitiesTable.tsx
  web_ui/frontend/components/ServerCapabilitiesTable.tsx
  web_ui/frontend/components/configuration/Fields/ObjectField/ObjectField.tsx
  web_ui/frontend/components/graphs/GraphOverlay.tsx
  web_ui/frontend/components/layout/Main.tsx
  web_ui/frontend/components/layout/Navigation/AppBar/AppBar.tsx
  web_ui/frontend/components/layout/Navigation/AppBar/BurgerMenu.tsx
  web_ui/frontend/components/layout/Navigation/AppBar/NavigationItem.tsx
  web_ui/frontend/components/layout/Navigation/AppBar/index.ts
  web_ui/frontend/components/layout/Navigation/Navigation.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/AboutMenu.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/Menu.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/NavigationItem.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/Sidebar.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/UserMenu.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/index.tsx
  web_ui/frontend/components/layout/Navigation/index.ts
  web_ui/frontend/components/layout/OriginSidebar.tsx
  web_ui/frontend/components/layout/PaddedContent.tsx
  web_ui/frontend/components/layout/Sidebar/ButtonLink.tsx
  web_ui/frontend/components/layout/Sidebar/index.tsx
  web_ui/frontend/components/layout/index.ts
  web_ui/frontend/helpers/login.ts
Labels: enhancement, javascript, origin, registry, web-ui

#1881 Fix typos
  web_ui/frontend/components/layout/Navigation/AppBar/NavigationItem.tsx
  web_ui/frontend/components/layout/Navigation/Sidebar/NavigationItem.tsx
Labels: bug

#1877 Use alma9 container for building prod pelican-server binaries
  images/Dockerfile
Labels: infrastructure

#1869 Server hot restart API with unit tests
  swagger/pelican-swagger.yaml
  web_ui/frontend/app/config/Config.tsx
  web_ui/frontend/app/config/components/RestartBox.tsx
  web_ui/frontend/app/config/components/index.ts
  web_ui/frontend/helpers/api.ts
  web_ui/ui.go
  web_ui/ui_test.go
Labels: enhancement, cache, origin, director, registry, web-ui

#1849 Docs Overhaul
  docs/pages/_meta.json
  docs/pages/about-pelican.mdx
  docs/pages/about-pelican/_meta.json
  docs/pages/about-pelican/core-concepts.mdx
  docs/pages/core-concepts.mdx
  docs/pages/faq.mdx
  docs/pages/federating-your-data.mdx
  docs/pages/federating-your-data/_meta.json
  docs/pages/federating-your-data/choosing-namespaces.mdx
  docs/pages/federating-your-data/origin.mdx
  docs/pages/getting-data-with-pelican.mdx
  docs/pages/getting-data-with-pelican/_meta.json
  docs/pages/getting-data-with-pelican/client.mdx
  docs/pages/getting-data-with-pelican/fsspec.mdx
  docs/pages/getting-started.mdx
  docs/pages/getting-started/accessing-data.mdx
  docs/pages/index.mdx
  docs/pages/operating-a-federation.mdx
  docs/pages/operating-a-federation/cache.mdx
  docs/pages/operating-a-federation/director.mdx
  docs/pages/operating-a-federation/registry.mdx
  docs/public/aggregated-objects.png
Labels: documentation, Facilitation

#1904 Fix typo in FAQ page
  docs/pages/faq.mdx
Labels: documentation

#1861 Add prefix restrictions on caches
  config/config.go
  director/director.go
  director/director_test.go
  director/registry_periodic_query.go
  director/registry_periodic_query_test.go
  docs/parameters.yaml
  launchers/director_serve.go
  param/parameters.go
  param/parameters_struct.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_db_test.go
Labels: enhancement, director, registry, security

#1886 Add default parameters check
  .github/scripts/validate-defaults/main.py
  .github/scripts/validate-defaults/requirements.txt
  .github/workflows/validate-parameters.yaml
  docs/parameters.yaml
Labels: bug, documentation

#1845 Add 'pelican enables researchers to...' blurb in index page
  docs/pages/about-pelican.mdx
Labels: documentation, Facilitation

#1885 Rejected Advertisement Metric
  director/director.go
  metrics/director.go
Labels: enhancement, director

#1748 Server-side key refresh and update registered public keys from origin server
  client/handle_http.go
  cmd/generate_keygen.go
  cmd/generate_keygen_test.go
  cmd/registry_client.go
  config/config.go
  config/encrypted.go
  config/encrypted_test.go
  config/init_server_creds.go
  config/init_server_creds_test.go
  director/director_test.go
  director/origin_api_test.go
  director/stat_test.go
  docs/parameters.yaml
  launcher_utils/key_refresh_and_update_namespace_pubkey.go
  launcher_utils/register_namespace_test.go
  launchers/launcher.go
  origin/origin_db_test.go
  param/parameters.go
  param/parameters_struct.go
  registry/client_commands.go
  registry/client_commands_test.go
  registry/registry.go
  registry/registry_db.go
  registry/registry_pubkey_update.go
  registry/registry_test.go
  token/token_create.go
  token/token_create_test.go
  web_ui/prometheus_test.go
  web_ui/ui_test.go
Labels: enhancement, origin, registry, go, security

#1927 Move `ticker.Stop()` into goroutine
  server_utils/monitor.go
  server_utils/server_utils.go
Labels: bug, critical

#1887 Add configuration for Prometheus to limit cardinality
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  web_ui/prometheus.go
Labels: enhancement

#1926 Install custom XRootD directly from Kojihub RPMs
  images/Dockerfile
  images/dev.Dockerfile
Labels: internal, dependencies, container, lotman

#1878 Improve memory usage of the "stat cache"
  client/director.go
  client/fed_linux_test.go
  client/handle_http.go
  cmd/plugin_test.go
  config/logging.go
  config/resources/defaults.yaml
  director/advertise_test.go
  director/cache_ads.go
  director/cache_ads_test.go
  director/director.go
  director/director_api.go
  director/resources/director-public.yaml
  director/sort.go
  director/sort_test.go
  director/stat.go
  director/stat_stress_test.go
  director/stat_test.go
  docs/parameters.yaml
  github_scripts/get_put_test.sh
  local_cache/cache_test.go
  metrics/director.go
Labels: bug

#1936 Fixes for the director tests
  config/config.go
  director/monitor.go
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  web_ui/ui.go
  xrootd/authorization.go
  xrootd/resources/xrootd-origin.cfg
  xrootd/xrootd_config.go
Labels: bug, origin, director

#1890 Retry client requests to Director if we detect the Director is rebooting
  client/director.go
  client/director_test.go
  client/fed_test.go
  cmd/plugin.go
  config/config.go
  director/director.go
  docs/parameters.yaml
  fed_test_utils/fed.go
  launchers/cache_serve.go
  launchers/director_serve.go
  launchers/launcher.go
  launchers/origin_serve.go
  launchers/registry_serve.go
  origin/origin_ui.go
  param/parameters.go
  param/parameters_struct.go
  utils/web_utils.go
  web_ui/oauth2_client.go
  web_ui/ui.go
Labels: enhancement, client, director

#1910 Update dependencies for OSX GitHub Action
  github_scripts/osx_install.sh
Labels: infrastructure, internal

#1950 Bump dev docker image's xrdcl-pelican to v1.0.2
  images/dev.Dockerfile
Labels: internal, cache

#1923 Add Prestage Functionality to Client
  client/acquire_token.go
  client/fed_test.go
  client/handle_http.go
  client/handle_http_test.go
  client/main.go
  client/prestage.go
  client/resources/both-auth.yml
  cmd/object_ls.go
  cmd/object_prestage.go
  cmd/plugin_test.go
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/xrootd_config.go
Labels: enhancement, client

#1935 Plumb Lotman config through to XRootD purge plugin
  config/config.go
  config/config_test.go
  docs/parameters.yaml
  lotman/lotman.go
  lotman/lotman_linux.go
  lotman/lotman_test.go
  param/parameters.go
  param/parameters_struct.go
  utils/utils.go
  utils/utils_test.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/xrootd_config.go
Labels: cache, lotman

#1959 Install pelican dependencies in final stage container
  images/Dockerfile
Labels: bug, dependencies, critical, cache, container

#1967 Remove particularly verbose logging line
  director/director_api.go
Labels: director
