Repository PelicanPlatform/pelican, pull requests merged in 2025-02, with the labels that each got.

#1974 Switch xrootd-s3-http plugin to be built from source
  images/Dockerfile
  images/dev.Dockerfile
Labels: infrastructure

#1921 Simplify Linux install instructions
  docs/pages/install/linux-binary.mdx
Labels: documentation

#1922 Remove jargon from the credential management page
  docs/pages/advanced-usage/server.mdx
Labels: documentation

#1946 Don't build dev images on git tags, tag im with latest-itb and sha256
  .github/workflows/build-dev-container.yml
Labels: bug, infrastructure, container

#1943 Card List Updates
  web_ui/frontend/components/CardList.tsx
  web_ui/frontend/helpers/get.ts
Labels: enhancement

#1984 Use Server.Hostname as the prefix for origin/cache namespace registration
  cache/advertise.go
  launcher_utils/advertise.go
  launcher_utils/key_refresh_and_update_namespace_pubkey.go
  launchers/cache_serve.go
  launchers/origin_serve.go
  origin/advertise.go
  origin/origin_ui.go
  server_structs/director.go
Labels: cache, origin, registry

#1980 Fix Director Capabilities Display
  web_ui/frontend/app/director/components/DirectorDropdown.tsx
  web_ui/frontend/components/CapabilitiesDisplay.tsx
  web_ui/frontend/components/NamespaceCapabilitiesTable.tsx
  web_ui/frontend/helpers/util.ts
Labels: bug

#1992 Fix linter bug
  web_ui/frontend/components/CapabilitiesDisplay.tsx
Labels: bug

#1983 Update xrootd release version to 1.5.purge.osg
  images/Dockerfile
  images/dev.Dockerfile
Labels: enhancement

#1991 Pinned the goreleaser version to 2
  .github/workflows/release.yml
  .github/workflows/test-template.yml
  .github/workflows/test.yml
  .goreleaser.yml
Labels: infrastructure, internal

#1997 Update Server.XYZ docs to include all server components
  docs/parameters.yaml
Labels: documentation

#1988 Fix xrootd log level mapping bug and inherit from Pelican log level
  cmd/config_printer/config_printer_test.go
  config/config.go
  config/resources/defaults.yaml
  docs/parameters.yaml
  param/parameters.go
  param/parameters_struct.go
  xrootd/xrootd_config.go
  xrootd/xrootd_config_test.go
Labels: bug, enhancement, cache, origin, configuration

#1998 Spruce up description of `Shoveler.Enable` param
  docs/parameters.yaml
Labels: documentation

#1972 Clean up the container image build and testing process
  .github/workflows/build-dev-container.yml
  .github/workflows/build-images.yml
  .github/workflows/build-prod-container.yml
  images/Dockerfile
  images/build-stages.dot
  images/build-stages.svg
  images/dev.Dockerfile
Labels: infrastructure, internal

#2000 Run tests in more appropriate container images
  .github/workflows/build-and-test.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-macos-windows.yml
  github_scripts/citests.sh
  images/Dockerfile
  images/build-stages.dot
  images/build-stages.svg
  images/dev-config.yaml
Labels: test, infrastructure, internal

#2013 Install new plugin: xrdhttp-pelican v0.0.3
  images/Dockerfile
Labels: enhancement, cache, origin

#2016 Rebase on OSG 24 (#1858)
  images/Dockerfile
Labels: enhancement, container

#2019 Pin xrootd log levels in fed test and use typed params throughout
  fed_test_utils/fed.go
Labels: test, internal

#2002 Enable PROPFIND of Director health test API
  director/director.go
  director/director_test.go
  e2e_fed_tests/README.md
  e2e_fed_tests/director_test.go
  e2e_fed_tests/resources/both-public.yml
Labels: test, critical, cache, director, monitoring

#1891 K8SPhysicalHostName Error Message
  cmd/plugin.go
  cmd/plugin_test.go
Labels: error messages

#2026 Update OS X install of xrootd-s3-http to v0.2.1
  github_scripts/osx_install.sh
Labels: infrastructure, internal

#1947 Add Cache and Server Cards to Map
  web_ui/frontend/app/director/map/page.tsx
  web_ui/frontend/components/InformationSpan.tsx
  web_ui/frontend/components/Map/PopOutCard.tsx
  web_ui/frontend/components/Map/ServerCard.tsx
  web_ui/frontend/components/Map/ServerMap.tsx
  web_ui/frontend/components/Map/index.ts
Labels: enhancement

#1893 Geoip table
  web_ui/frontend/app/config/Config.tsx
  web_ui/frontend/app/director/components/GeoIpErrorTable.tsx
  web_ui/frontend/app/director/components/index.tsx
  web_ui/frontend/app/director/page.tsx
  web_ui/frontend/components/LatitudeLongitudePicker.tsx
  web_ui/frontend/components/Map/UpdateSinglePoint.tsx
  web_ui/frontend/components/configuration/Fields/ObjectField/GeoIPOverrideForm.tsx
  web_ui/frontend/components/configuration/Fields/ObjectField/IPMappingForm.tsx
  web_ui/frontend/components/configuration/util.ts
  web_ui/frontend/package-lock.json
Labels: enhancement

#2030 Attempted speedups for GHA PR runs
  .github/workflows/test-linux.yml
  .github/workflows/test-macos-windows.yml
  Makefile
Labels: infrastructure, internal

#1994 Remove tls authentication from caches
  cache/advertise.go
  cache/advertise_test.go
  config/resources/defaults.yaml
  config/resources/osdf.yaml
  director/director.go
  docs/parameters.yaml
  github_scripts/x509_test.sh
  param/parameters.go
  param/parameters_struct.go
  xrootd/resources/xrootd-cache.cfg
  xrootd/xrootd_config.go
Labels: cache

#1919 Refactor & Cleanup Origin Exports code
  server_utils/origin.go
  server_utils/origin_globus.go
  server_utils/origin_https.go
  server_utils/origin_posix.go
  server_utils/origin_s3.go
  server_utils/origin_test.go
  server_utils/origin_xroot.go
  server_utils/resources/globus-origins/multi-export-valid.yml
  server_utils/resources/globus-origins/single-export-invalid.yml
  server_utils/resources/globus-origins/single-export-valid.yml
  server_utils/resources/https-origins/multi-export.yml
  server_utils/resources/https-origins/single-export.yml
  server_utils/resources/s3-origins/env-var-mimic.yml
  server_utils/resources/s3-origins/export-volumes-valid.yml
  server_utils/resources/s3-origins/multi-export-valid.yml
  server_utils/resources/s3-origins/single-export-block.yml
  server_utils/resources/s3-origins/single-export-volume.yml
  server_utils/resources/xroot-origins/single-export-invalid.yml
  server_utils/resources/xroot-origins/single-export-valid.yml
Labels: internal, origin

#1985 Add federation token endpoint in Director, and implement routine for caches to fetch one
  cache/advertise.go
  config/config.go
  config/resources/defaults.yaml
  director/director.go
  director/director_test.go
  director/fed_token.go
  director/fed_token_test.go
  docs/parameters.yaml
  e2e_fed_tests/cache_test.go
  e2e_fed_tests/director_test.go
  launcher_utils/advertise.go
  launchers/cache_serve.go
  origin/advertise.go
  param/parameters.go
  param/parameters_struct.go
  registry/registry.go
  registry/registry_db.go
  server_structs/auth.go
  server_structs/xrootd_server.go
  server_utils/server_utils.go
  server_utils/server_utils_test.go
  swagger/pelican-swagger.yaml
Labels: enhancement, cache, director, security

#1917 Grafana Token API Access
  database/director.go
  database/server.go
  database/utils/utils.go
  director/director.go
  director/director_db.go
  director/director_db_test.go
  director/director_test.go
  director/migrations/20250103161929_create_db_tables.sql
  local_cache/cache_api.go
  server_structs/db.go
  swagger/pelican-swagger.yaml
  token/token_verify.go
  web_ui/authorization.go
  web_ui/database.go
  web_ui/ui.go
  web_ui/ui_test.go
Labels: enhancement, director, monitoring

#2037 Fix UI crashes
  web_ui/frontend/app/director/components/GeoIpErrorTable.tsx
  web_ui/frontend/app/director/metrics/components/StorageTable.tsx
Labels: bug, javascript, web-ui

#2038 Add /version endpoint to expose version and build info
  swagger/pelican-swagger.yaml
  web_ui/ui.go
Labels: enhancement

#1970 Log Pelican config on server startup
  config/config.go
Labels: enhancement, cache, origin, director, registry

#1981 Allow for Shoveler messages to be understood by monitoring packet handler.
  metrics/shoveler.go
  metrics/xrootd_metrics.go
  metrics/xrootd_metrics_test.go
  xrootd/xrootd_config.go
Labels: bug, monitoring

#2048 Use random cache port in TestFedServeCache
  cmd/fed_serve_cache_test.go
Labels: bug

#2050 Document restricted characters in fed prefixes
  docs/pages/federating-your-data/choosing-namespaces.mdx
Labels: documentation, Facilitation

#2053 Install `pelican-server` into `/usr/local/sbin`
  images/Dockerfile
Labels: bug, critical, cache, container

#2057 Do not assume the existence of XRootD (`xrootd`) when it is not necessary
  config/config.go
  config/mkdirall.go
Labels: bug, critical, director, registry, container

#2059 Add geoquery tool to Director containers
  images/Dockerfile
  scripts/geoquery.py
Labels: enhancement, director, container
